language: ruby
before_install:
  - sudo apt-get install libvips-dev
  - gem install bundler --version "~> 1.10"
rvm:
  - 2.1.5
script: "bundle exec rake ci"
cache:
  - apt
notifications:
  email:
    - lib-drs@duke.edu
bundler_args: --without production
