language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libvips-dev
  - gem install bundler -v '< 2'
bundler_args: --without production
rvm:
  - 2.3.1
before_script:
  - "cp spec/dummy/config/database.yml.travis spec/dummy/config/database.yml"
  - "psql -c 'create database travis_ci_test;' -U postgres"
script: "bundle exec rake ci"
env:
  - DDR_AUX_API_URL=http://localhost:3000/api
