language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libvips-dev
  - gem install bundler
bundler_args: --without production
rvm:
  - 2.3.1
script: "bundle exec rake ci"
env:
  - DDR_AUX_API_URL=http://localhost:3000/api
