development:
  adapter: solr
  url: http://127.0.0.1:<%= ENV['SOLR_DEVELOPMENT_PORT'] || 8983 %>/solr/solr-dev
test: &test
  adapter: solr
  url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/solr-test
production:
  adapter: solr
  url: http://production.server/solr/solr-prod
