# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c547872c9ca7873d386440a5516093b0c26b350b7d94c3e02955bfbe9cfeecfa0b0252466c3467f7c3ec4d1e4abe70ddf8a5a70b6c1648718b5cf2ae61e9bd9e

test:
  secret_key_base: e5aff478f4b057784df800c1014395c6261e17767f57cae5cc1d6389ed50fc1ff64d211217b639715b8db396650cd116eb50f1e6c1a0418f62f9fdb384efc72e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
