development:
  url: http://localhost:8983/solr/development
test: 
  url: <%= "http://localhost:#{ENV['TEST_JETTY_PORT'] || 8983}/solr/test" %>
production:
  url: http://your.production.server:8080/bl_solr/core0 
